language: node_js
node_js:
    - 12.13.1

cache: npm

install: 
    - npm ci

script: 
    - ng test
    - npm run compodoc


deploy: 
    provider: pages
    skip-cleanup: true
    github-token: $token
    on:
        branches: master