language: node_js
node_js:
 - "12.13.1"

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - npm install @angular/cli
  - npm install @compodoc/compodoc — save-dev

cache:
  npm: true
  directories:
    - node_modules

script:
  - ng build --prod
  - npm run deploy
  - npm run compodoc
  - npm run deploy


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  local-dir: /documentation
  on: