
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.13.1
    steps:
      - checkout
      - run:
          name: Install Node Packages
          command: npm install
      - run:
          name: Install Angular
          command: echo y | sudo npm install -g @angular/cli
      - run:
          name: Install compodoc
          command: npm install @compodoc/compodoc
      - run:
          name: Install gh-Packages
          command: npm install gh-pages
      - run:
          name: Build Angular Application
          command: ng build --prod && npm run compodoc && npm run deploy
      - run:
          name: Add GIT CONFIG
          command: git config --global user.email EMAIL && git config --global user.name NAME
            