version: 2.1
jobs:
docs-build:
  docker:
    - image: node
  steps:
    - checkout
    - run:
        name: Install dependencies
        command: npm install
    
    - run: 
        name: Install Angular
        command: echo y | sudo npm install -g @angular/cli
    - run:
        name: Build docs
        command: ng build --prod && npm run compodoc



